apiVersion: v2
name: io-functions-email-validator-chart
description: An example of microserivce that takes secrets from KeyVault
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
- name: aks-microservice-chart-blueprint
  version: 1.8.2
  repository: "https://github.com/pagopa/aks-microservice-chart-blueprint"
